export const ADMIN_EMAIL = 'mohamedyakhou40@gmail.com';
export const ADMIN_PASSWORD = '052307My';

export const WILAYAS = [
  { id: 1, name: "أدرار", nameEn: "Adrar" },
  { id: 2, name: "الشلف", nameEn: "Chlef" },
  { id: 3, name: "الأغواط", nameEn: "Laghouat" },
  { id: 4, name: "أم البواقي", nameEn: "Oum El Bouaghi" },
  { id: 5, name: "باتنة", nameEn: "Batna" },
  { id: 6, name: "بجاية", nameEn: "Bejaia" },
  { id: 7, name: "بسكرة", nameEn: "Biskra" },
  { id: 8, name: "بشار", nameEn: "Bechar" },
  { id: 9, name: "البليدة", nameEn: "Blida" },
  { id: 10, name: "البويرة", nameEn: "Bouira" },
  { id: 11, name: "تمنراست", nameEn: "Tamanrasset" },
  { id: 12, name: "تبسة", nameEn: "Tebessa" },
  { id: 13, name: "تلمسان", nameEn: "Tlemcen" },
  { id: 14, name: "تيارت", nameEn: "Tiaret" },
  { id: 15, name: "تيزي وزو", nameEn: "Tizi Ouzou" },
  { id: 16, name: "الجزائر", nameEn: "Alger" },
  { id: 17, name: "الجلفة", nameEn: "Djelfa" },
  { id: 18, name: "جيجل", nameEn: "Jijel" },
  { id: 19, name: "سطيف", nameEn: "Setif" },
  { id: 20, name: "سعيدة", nameEn: "Saida" },
  { id: 21, name: "سكيكدة", nameEn: "Skikda" },
  { id: 22, name: "سيدي بلعباس", nameEn: "Sidi Bel Abbes" },
  { id: 23, name: "عنابة", nameEn: "Annaba" },
  { id: 24, name: "قالمة", nameEn: "Guelma" },
  { id: 25, name: "قسنطينة", nameEn: "Constantine" },
  { id: 26, name: "المدية", nameEn: "Medea" },
  { id: 27, name: "مستغانم", nameEn: "Mostaganem" },
  { id: 28, name: "المسيلة", nameEn: "M'Sila" },
  { id: 29, name: "معسكر", nameEn: "Mascara" },
  { id: 30, name: "ورقلة", nameEn: "Ouargla" },
  { id: 31, name: "وهران", nameEn: "Oran" },
  { id: 32, name: "البيض", nameEn: "El Bayadh" },
  { id: 33, name: "إليزي", nameEn: "Illizi" },
  { id: 34, name: "برج بوعريريج", nameEn: "Bordj Bou Arreridj" },
  { id: 35, name: "بومرداس", nameEn: "Boumerdes" },
  { id: 36, name: "الطارف", nameEn: "El Tarf" },
  { id: 37, name: "تندوف", nameEn: "Tindouf" },
  { id: 38, name: "تيسمسيلت", nameEn: "Tissemsilt" },
  { id: 39, name: "الوادي", nameEn: "El Oued" },
  { id: 40, name: "خنشلة", nameEn: "Khenchela" },
  { id: 41, name: "سوق أهراس", nameEn: "Souk Ahras" },
  { id: 42, name: "تيبازة", nameEn: "Tipaza" },
  { id: 43, name: "ميلة", nameEn: "Mila" },
  { id: 44, name: "عين الدفلى", nameEn: "Ain Defla" },
  { id: 45, name: "النعامة", nameEn: "Naama" },
  { id: 46, name: "عين تموشنت", nameEn: "Ain Temouchent" },
  { id: 47, name: "غرداية", nameEn: "Ghardaia" },
  { id: 48, name: "غليزان", nameEn: "Relizane" },
  { id: 49, name: "تيميمون", nameEn: "Timimoun" },
  { id: 50, name: "برج باجي مختار", nameEn: "Bordj Badji Mokhtar" },
  { id: 51, name: "أولاد جلال", nameEn: "Ouled Djellal" },
  { id: 52, name: "بني عباس", nameEn: "Beni Abbes" },
  { id: 53, name: "عين صالح", nameEn: "In Salah" },
  { id: 54, name: "عين قزام", nameEn: "In Guezzam" },
  { id: 55, name: "توقرت", nameEn: "Touggourt" },
  { id: 56, name: "جانت", nameEn: "Djanet" },
  { id: 57, name: "المغير", nameEn: "El M'Ghair" },
  { id: 58, name: "النعمة", nameEn: "El Meniaa" },
];

export const USER_ROLES = {
  ADMIN: 'admin',
  DRIVER: 'driver',
  CUSTOMER: 'customer',
};

export const COLORS = {
  primary: '#1E88E5',
  primaryDark: '#1565C0',
  primaryLight: '#BBDEFB',
  accent: '#FF6D00',
  accentLight: '#FF8F00',
  success: '#43A047',
  successLight: '#66BB6A',
  error: '#E53935',
  warning: '#FB8C00',
  background: '#F5F7FA',
  surface: '#FFFFFF',
  text: '#1A1A2E',
  textSecondary: '#6B7280',
  border: '#E5E7EB',
  white: '#FFFFFF',
  black: '#000000',
  grey: '#9CA3AF',
  lightGrey: '#F0F2F5',
};

export const VEHICLE_TYPES = [
  { id: 'motorcycle', name: 'دراجة نارية', emoji: '🏍️' },
  { id: 'car', name: 'سيارة', emoji: '🚗' },
  { id: 'bicycle', name: 'دراجة هوائية', emoji: '🚲' },
  { id: 'walking', name: 'مشي', emoji: '🚶' },
];

export const ITEM_TYPES = [
  { id: 'food', name: 'طعام', emoji: '🍔' },
  { id: 'clothes', name: 'ملابس', emoji: '👕' },
  { id: 'documents', name: 'وثائق', emoji: '📄' },
  { id: 'electronics', name: 'إلكترونيات', emoji: '📱' },
  { id: 'groceries', name: 'بقالة', emoji: '🛒' },
  { id: 'medicine', name: 'أدوية', emoji: '💊' },
  { id: 'other', name: 'أخرى', emoji: '📦' },
];
